### ISSUE TITLE
feat/add favorites

### ISSUE THREAD

**Issue by alexa-w** [psychonauts/pluck#30]

**Comment by alexa-w** [comment]
As a user, I should be able to add a plant to my "favorites".
As a user, I should be able to view each plant in my "favorites".

**Comment by cskladz** [comment]
As a user, I should be able to add a plant to my "favorites". -- Complete
As a user, I should be able to view each plant in my "favorites".
As a user, I should be able have some indication when I click the favorite button that my plant was Favorited
